version: "3"

services:
  userapi:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      SERVICES: userapi
      PORT: 8000
    ports:
      - 8000:8000
    networks:
      - internal

networks:
  internal:

volumes:
  data:
